import type { Metadata } from "next";
import { ReactNode } from "react";

import { Header } from "@/features/layout";
import { Providers } from "@/providers";

import { poiret } from "../fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={poiret.className}>
      <head>
        <title>WhereIsAGift</title>
      </head>
      <body className="bg-[url('../assets/paperFacture.png')]  bg-repeat bg-[length:600px_600px] bg-center animate-scrollBackground min-h-screen">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
