import type { Metadata } from "next";
import { Poiret_One } from "next/font/google";

import "./globals.css";
import { Header } from "components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poiret = Poiret_One({
  display: "swap",
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poiret.className}>
      <head></head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
