name: Build and Push Next.js to GHCR

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/whereisagift/whereisagift-frontend
          TAG=${{ github.sha }}

          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout whereisagift-devops repository
        uses: actions/checkout@v4
        with:
          repository: whereisagift/whereisagift-devops
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Update frontend version in whereisagift-devops
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          
          if [[ "$BRANCH_NAME" == "main" ]]; then
            DOCKER_COMPOSE_PATH="./frontend/production/docker-compose.yml"
            TAG="production"
          else
            DOCKER_COMPOSE_PATH="./frontend/development/docker-compose.yml"
            TAG="develop"
          fi
          
          # Обновляем docker-compose.yml, заменяя версию образа
          sed -i "s|image: ghcr.io/whereisagift/whereisagift-frontend:[^ ]*|image: ghcr.io/whereisagift/whereisagift-frontend:${{ github.sha }}|" "$DOCKER_COMPOSE_PATH"
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "$DOCKER_COMPOSE_PATH"
          git commit -m "Update frontend image version in $DOCKER_COMPOSE_PATH to ${{ github.sha }}"
          git push
