name: Build and Push Next.js to GHCR

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/whereisagift/whereisagift-frontend
          TAG=${{ github.sha }}
          BRANCH_TAG=${{ github.ref_name == 'main' && 'production' || 'develop' }}

          # Build the Docker image with the necessary tags (SHA, latest, production/develop)
          docker build -f ./deploy/Dockerfile --build-arg NEXT_PUBLIC_TELEGRAM_BOT=${{ secrets.NEXT_PUBLIC_TELEGRAM_BOT }} -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest -t $IMAGE_NAME:$BRANCH_TAG .

          # Push the Docker images with the tags
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$BRANCH_TAG

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: Trigger application deployment
        run: |
          curl -X 'POST' \
          '${{ secrets.DOKPLOY_TRIGGER_API }}' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: ${{ secrets.DOKPLOY_TOKEN }}' \
          -d '{"applicationId": "${{ secrets.DOKPLOY_APP_ID }}"}'
