name: Build Frontend

permissions:
  packages: write

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/YOUR_ORG/whereisagift-frontend
          VERSION=$(git rev-parse --short HEAD)
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Checkout whereisagift-devops repository
        uses: actions/checkout@v4
        with:
          repository: whereisagift/whereisagift-devops
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update frontend version in whereisagift-devops
        run: |
          echo "FRONTEND_VERSION=$(git rev-parse --short HEAD)" > frontend.version
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add frontend.version
          git commit -m "Update frontend version to $(git rev-parse --short HEAD)"
          git push
