name: Build and Push Next.js to GHCR

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/whereisagift/whereisagift-frontend
          tags: |
            type=sha,prefix=${{ github.ref_name == 'main' && 'production' || 'develop' }}-,
            ${{ github.ref_name == 'main' && 'production' || 'develop' }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          file: ./deploy/Dockerfile
          cache-to: type=gha,mode=max
          cache-from: type=gha
          build-args: |
            NEXT_PUBLIC_TELEGRAM_BOT=${{ secrets.NEXT_PUBLIC_TELEGRAM_BOT }}

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: Trigger application deployment
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DOKPLOY_TRIGGER_API }}
          method: POST
          customHeaders: |
            {"x-api-key": "${{ secrets.DOKPLOY_TOKEN }}"}
          data: |
            {"applicationId": "${{ secrets.DOKPLOY_APP_ID }}"}
